name: 'Terraform_fmt' 
 
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  terraform:
    name: 'Terraform_fmt'
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
       cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
     
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
    
    - name: Terraform_Format_correct
      id: fmt_check
      run: terraform fmt 
